env:
  global:
    - CC_TEST_REPORTER_ID=2c05e78a4e2bcf3600b85d1e26789e3217e847362b310b7dc03933f295662626
language: node_js
node_js:
- "6.11.2"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm install
- nyc --reporter=lcov mocha
- gulp
- gulp debug
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT